#hosts.yaml
---
Edge01:
  hostname: 192.168.0.10
  groups:
    - cisco
    - s1
  data:
    site_code: s1
    device_role: wan_router      # Options:  "core_switch"  "access_switch" "wan_router"
    host_name: s1-wan-rt01
    edge_node: 1 #To create origin comm
    global_rid: "10.0.0.1"

    ############################################ Breakout ############################################

    intranet_primary: "true" # "true" or "false"
    internet_primary: "true" # "true" or "false"

    ############################################ Loopback Interfaces ############################################
    loopback_interfaces:
    - name: "Loopback0"
      description: "*** Global Loopback ***"
      ip: "10.0.0.1"
      sm: "255.255.255.255"
    #  vrf: "INTERNET-VRF"

    ############################################ Routed Interfaces ############################################

    routed_interfaces:
    - name: "Ethernet0/1"
      status: "true" # "true" or "false"
      description: "***Uplink WAN-ISP-X-Circuid-IDXXXXX***"
      ip: "200.1.10.1"
      sm: "255.255.255.0"
      vrf: "INTERNET-VRF"
    
    - name: "Ethernet0/0"
      status: "true"
      description: "***Uplink CSWxWAN-RT01***"
      ip: "10.1.0.0"
      sm: "255.255.255.254"


    ############################################ Tunnel Interfaces - ZS ############################################
    # Please see Regional vars
    tunnel_interfaces_zs:
    - name: "Tunnel10"
      description: "*** Tunnel to primary ZEN proxy ***"
      ip: "172.16.10.2"
      sm: "255.255.255.252"
      tu_source: "Ethernet0/1"

    - name: "Tunnel20"
      description: "*** Tunnel to secondary ZEN proxy ***"
      ip: "172.16.20.2"
      sm: "255.255.255.252"
      tu_source: "Ethernet0/1"

    ############################################ Tunnel Interfaces - DMPVN ############################################
    # Please see Global and Regional vars
    tunnel_interfaces_phs:
    - name: "Tunnel110"
      description: "*** R1-HUB1 - PRIMARY PH DMVPN SPOKE TUNNEL ***"
      ip: "10.1.110.2"
      sm: "255.255.255.0"           
      tu_source: "Ethernet0/1"

    - name: "Tunnel210"
      description: "*** R1-HUB2 - PRIMARY PH DMVPN SPOKE TUNNEL ***"
      ip: "10.2.210.2"
      sm: "255.255.255.0"
      tu_source: "Ethernet0/1"


    ############################################ Static routes #############################################
    static_routes:
    - name: Default Route
      ip: "0.0.0.0"
      sm: "0.0.0.0"
      gw: "200.10.1.254"
      vrf: "INTERNET-VRF"

    ############################################ OSPF #############################################

    ospf_processes:
      - pid: 1
        rid: "10.0.0.1"
        interfaces_enabled:
          - name: "Ethernet0/0"
        networks:
          - address: "10.0.0.1"
            netmask: 0.0.0.0
            area: 0 
          - address: "10.1.0.0"
            netmask: 0.0.0.0
            area: 0 

    ############################################ BGP #############################################
    # eBGP HUB Peers defined inside region variables file 
    bgp_local_as: "65510"
    bgp_rid: "10.0.0.1"

    ibgp_peers:
      - address: "10.10.0.2"
        description: "*** iBGP Peer ***" 
        update_source: "Ethernet0/1"
    bgp_networks:
      - address: "10.1.0.0"
        netmask: "255.255.0.0"



Edge02:
  hostname: 192.168.0.10
  groups:
    - cisco
    - s1
  data:
    site_code: s1
    device_role: wan_router      # Options:  "core_switch"  "access_switch" "wan_router"
    host_name: s1-wan-rt02
    edge_node: 1 #To create origin comm
    global_rid: "10.0.0.2"

    ############################################ Breakout ############################################

    intranet_primary: "true" # "true" or "false"
    internet_primary: "true" # "true" or "false"

    ############################################ Loopback Interfaces ############################################
    loopback_interfaces:
    - name: "Loopback0"
      description: "*** Global Loopback ***"
      ip: "10.0.0.2"
      sm: "255.255.255.255"
    #  vrf: "INTERNET-VRF"

    ############################################ Routed Interfaces ############################################

    routed_interfaces:
    - name: "Ethernet0/1"
      status: "true" # "true" or "false"
      description: "***Uplink WAN-ISP-X-Circuid-IDXXXXX***"
      ip: "200.2.11.1"
      sm: "255.255.255.0"
      vrf: "INTERNET-VRF"
    
    - name: "Ethernet0/0"
      status: "true"
      description: "***Uplink CSWxWAN-RT02***"
      ip: "10.1.0.4"
      sm: "255.255.255.254"


    ############################################ Tunnel Interfaces - ZS ############################################
    # Please see Regional vars
    tunnel_interfaces_zs:
    - name: "Tunnel10"
      description: "*** Tunnel to primary ZEN proxy ***"
      ip: "172.16.10.6"
      sm: "255.255.255.252"
      tu_source: "Ethernet0/1"

    - name: "Tunnel20"
      description: "*** Tunnel to secondary ZEN proxy ***"
      ip: "172.16.20.6"
      sm: "255.255.255.252"
      tu_source: "Ethernet0/1"

    ############################################ Tunnel Interfaces - DMPVN ############################################
    # Please see Global and Regional vars
    tunnel_interfaces_phs:
    - name: "Tunnel110"
      description: "*** HUB1 - PRIMARY DMVPN SPOKE TUNNEL ***"
      ip: "10.1.110.2"
      sm: "255.255.255.0"           
      tu_source: "Ethernet0/1"

    - name: "Tunnel210"
      description: "*** HUB2 - PRIMARY DMVPN SPOKE TUNNEL ***"
      ip: "10.2.210.2"
      sm: "255.255.255.0"
      tu_source: "Ethernet0/1"


    ############################################ Static routes #############################################
    static_routes:
    - name: Default Route
      ip: "0.0.0.0"
      sm: "0.0.0.0"
      gw: "200.10.1.254"
      vrf: "INTERNET-VRF"

    ############################################ OSPF #############################################

    ospf_processes:
      - pid: 1
        rid: "10.0.0.2"
        interfaces_enabled:
          - name: "Ethernet0/0"
        networks:
          - address: "10.0.0.2"
            netmask: 0.0.0.0
            area: 0 
          - address: "10.1.0.4"
            netmask: 0.0.0.0
            area: 0 

    ############################################ BGP #############################################
    # eBGP HUB Peers defined inside region variables file 
    bgp_local_as: "65510"
    bgp_rid: "10.0.0.2"

    ibgp_peers:
      - address: "10.10.0.2"
        description: "*** iBGP Peer ***" 
        update_source: "Ethernet0/0"
    bgp_networks:
      - address: "10.1.0.0"
        netmask: "255.255.0.0"

Csw01:
  hostname: 192.168.0.11
  groups:
    - cisco
    - s1
  data:
    site_code: s1
    device_role: core_switch      # Options:  "core_switch"  "access_switch" "wan_router"
    host_name: s1-csw01
    global_rid: "10.0.0.3"

    ############################################ VLANS ###################################################
    vlans:
      - name: Wired-Corp
        id: 101
      - name: Wireless-Corp
        id: 201
      - name: Servers
        id: 301
      - name: Wireless-Guest
        id: 666
      - name: Uplink-CSWxCSW
        id: 800
      - name: Mgmt-Meraki-WAP
        id: 997
      - name: Mgmt-Cisco-SW
        id: 998
      - name: Trunk_Unused_Native_VLAN # Trunks only
        id: 13



    ############################################ SVI Interfaces ############################################
    svi_interfaces:
    - name: Vlan800
      description: "***Uplink-CSWxCSW - Vlan800***"
      ip: "10.1.0.2"
      sm: "255.255.255.254"

    - name: Vlan998
      description: "***ManagementPort-Vlan998***"
      ip: "10.1.253.2"
      sm: "255.255.255.0"
      helper_enable: True # True or False and it depends on helper_addresses var exists
      hsrp_ip: "10.1.253.1"
      hsrp_prio: 110

    - name: Vlan101
      description: "***Data User - Vlan101***"
      ip: "10.1.1.2"
      sm: "255.255.255.0"
      helper_enable: True # True or False and it depends on helper_addresses var exists
      hsrp_ip: "10.1.1.1"
      hsrp_prio: 110


    ############################################ Loopback Interfaces ############################################
    loopback_interfaces:
    - name: "Loopback0"
      description: "*** Global Loopback ***"
      ip: "10.0.0.3"
      sm: "255.255.255.255"
    #  vrf: "INTERNET-VRF"


    ############################################ Routed Interfaces ############################################
    routed_interfaces:
    - name: "Ethernet0/0"
      description: "***Uplink CSWxWAN-EDGE1***"
      ip: "10.1.0.1"
      sm: "255.255.255.254"


    ############################################ Static routes #############################################
    #static_routes:
    #- name: Default Route
    #  ip: "0.0.0.0"
    #  sm: "0.0.0.0"
    #  gw: "10.0.255.1"



    #uplink_interfaces:
    # name examples: Port-channel12 or GigabitEthernet2/0/11
    #- name: Port-channel1
    #  description: "***Uplink CSWxASW***"
    #  vlan_range: "101,201,301,666,997,998"
    #  native_vid: "13"


    port_channel_interfaces:
    - name: "Port-channel1"
      description: "***Uplink CSWxASW***"
      vlan_range: "101,201,301,666,997,998"
      #native_vid: "13"
      pono: "1"
      po_mode: "active"
      po_int_members:
        - name: "Ethernet1/0"
          description: "***Uplink CSW01-e1/0 <--> ASW01 e1/0 - Po1***"
        - name: "Ethernet1/1"
          description: "***Uplink CSW01-e1/1 <--> ASW01 e1/1 - Po1***"

    - name: "Port-channel10"
      description: "***Uplink CSW01xCSW02***"
      vlan_range: "101,201,301,666,800,997,998"
      #native_vid: "13"
      pono: "10"
      po_mode: "active"
      po_int_members:
        - name: "Ethernet0/2"
          description: "***Uplink CSW01-e0/2 <--> CSW02-e0/2 - Po10***"
        - name: "Ethernet0/1"
          description: "***Uplink CSW01-e0/1 <--> CSW02-e0/1 - Po10***"

    ospf_processes:
      - pid: 1
        rid: "10.0.0.3"
        interfaces_enabled:
          - name: Ethernet0/0
          - name: Vlan800
        networks:
          - address: "10.0.0.3" #Loopback
            netmask: 0.0.0.0
            area: 0
          - address: 10.1.0.1 #WAN_RTxSWC
            netmask: 0.0.0.0
            area: 0
          - address: 10.1.0.2 #SWCxSWC
            netmask: 0.0.0.0
            area: 0
          - address: 10.1.253.2 #MGMT ASW 
            netmask: 0.0.0.0
            area: 0
          - address: 10.1.101.2 #User data vlan 101 
            netmask: 0.0.0.0
            area: 0

Csw02:
  hostname: 192.168.0.15
  groups:
    - cisco
    - s1
  data:
    site_code: s1
    device_role: core_switch      # Options:  "core_switch"  "access_switch" "wan_router"
    host_name: s1-csw02
    global_rid: "10.0.0.4"

    ############################################ VLANS ###################################################
    vlans:
      - name: Wired-Corp
        id: 101
      - name: Wireless-Corp
        id: 201
      - name: Servers
        id: 301
      - name: Wireless-Guest
        id: 666
      - name: Uplink-CSWxCSW
        id: 800
      - name: Mgmt-Meraki-WAP
        id: 997
      - name: Mgmt-Cisco-SW
        id: 998
      - name: Trunk_Unused_Native_VLAN # Trunks only
        id: 13



    ############################################ SVI Interfaces ############################################
    svi_interfaces:
    - name: Vlan800
      description: "***Uplink-CSWxCSW - Vlan800***"
      ip: "10.1.0.3"
      sm: "255.255.255.254"

    - name: Vlan998
      description: "***ManagementPort-Vlan998***"
      ip: "10.1.253.3"
      sm: "255.255.255.0"
      helper_enable: True # True or False and it depends on helper_addresses var exists
      hsrp_ip: "10.1.253.1"
      hsrp_prio: 110

    - name: Vlan101
      description: "***Data User - Vlan101***"
      ip: "10.1.1.3"
      sm: "255.255.255.0"
      helper_enable: True # True or False and it depends on helper_addresses var exists
      hsrp_ip: "10.1.1.1"
      hsrp_prio: 110


    ############################################ Loopback Interfaces ############################################
    loopback_interfaces:
    - name: "Loopback0"
      description: "*** Global Loopback ***"
      ip: "10.0.0.4"
      sm: "255.255.255.255"
    #  vrf: "INTERNET-VRF"


    ############################################ Routed Interfaces ############################################
    routed_interfaces:
    - name: "Ethernet0/0"
      description: "***Uplink CSWxWAN-EDGE1***"
      ip: "10.1.0.5"
      sm: "255.255.255.254"


    ############################################ Static routes #############################################
    #static_routes:
    #- name: Default Route
    #  ip: "0.0.0.0"
    #  sm: "0.0.0.0"
    #  gw: "10.0.255.1"



    #uplink_interfaces:
    # name examples: Port-channel12 or GigabitEthernet2/0/11
    #- name: Port-channel1
    #  description: "***Uplink CSWxASW***"
    #  vlan_range: "101,201,301,666,997,998"
    #  native_vid: "13"


    port_channel_interfaces:
    - name: "Port-channel1"
      description: "***Uplink CSWxASW***"
      vlan_range: "101,201,301,666,997,998"
      #native_vid: "13"
      pono: "1"
      po_mode: "active"
      po_int_members:
        - name: "Ethernet1/0"
          description: "***Uplink CSW01-e1/0 <--> ASW02 e1/0 - Po1***"
        - name: "Ethernet1/1"
          description: "***Uplink CSW01-e1/1 <--> ASW02 e1/1 - Po1***"

    - name: "Port-channel10"
      description: "***Uplink CSW01xCSW02***"
      vlan_range: "101,201,301,666,800,997,998"
      #native_vid: "13"
      pono: "10"
      po_mode: "passive"
      po_int_members:
        - name: "Ethernet0/2"
          description: "***Uplink CSW02-e0/2 <--> CSW01-e0/2 - Po10***"
        - name: "Ethernet0/1"
          description: "***Uplink CSW02-e0/1 <--> CSW01-e0/1 - Po10***"

    ospf_processes:
      - pid: 1
        rid: "10.0.0.4"
        interfaces_enabled:
          - name: Ethernet0/0
          - name: Vlan800
        networks:
          - address: "10.0.0.4" #Loopback
            netmask: 0.0.0.0
            area: 0
          - address: 10.1.0.5 #WAN_RTxSWC
            netmask: 0.0.0.0
            area: 0
          - address: 10.1.0.3 #SWCxSWC
            netmask: 0.0.0.0
            area: 0
          - address: 10.1.253.3 #MGMT ASW 
            netmask: 0.0.0.0
            area: 0
          - address: 10.1.101.3 #User data vlan 101 
            netmask: 0.0.0.0
            area: 0



Asw01:
  hostname: 192.168.0.12
  groups:
    - cisco
    - s1
  data:
    site_code: s1
    device_role: access_switch      # Options:  "core_switch"  "access_switch" "wan_router"
    host_name: s1-asw01

    ############################################ VLANS ###################################################
    vlans:
      - name: Wired-Corp
        id: 101
      - name: Wireless-Corp
        id: 201
      - name: Servers
        id: 301
      - name: Wireless-Guest
        id: 666
      - name: Mgmt-Meraki-WAP
        id: 997
      - name: Mgmt-Cisco-SW
        id: 998
      - name: Trunk_Unused_Native_VLAN # Trunks only
        id: 13



    ############################################ SVI Interfaces ############################################
    svi_interfaces:
    - name: Vlan998
      description: "***ManagementPort-Vlan998***"
      ip: "10.1.253.4"
      sm: "255.255.255.0"

    ############################################ Static routes #############################################
    static_routes:
    - name: Default Route
      ip: "0.0.0.0"
      sm: "0.0.0.0"
      gw: "10.1.253.1"


    #uplink_interfaces:
    # name examples: Port-channel12 or GigabitEthernet2/0/11
    #- name: Port-channel1
    #  description: "***Uplink CSWxASW***"
    #  vlan_range: "101,201,301,666,997,998"
    #  native_vid: "13"


    port_channel_interfaces:
    - name: "Port-channel1"
      description: "***Uplink CSWxASW***"
      vlan_range: "101,201,301,666,997,998"
      #native_vid: "13"
      pono: "1"
      po_mode: "passive"
      po_int_members:
        - name: "Ethernet1/0"
          description: "***Uplink ASW01-e1/0 <--> CSW01-e1/0 - Po1***"
        - name: "Ethernet1/1"
          description: "***Uplink ASW01-e1/1 <--> CSW01-e1/1 - Po1***"

    ############################################ User Data Interfaces ########################################
    userdata_pvid: 101
    userdata_int_desc: "***UserDataVlan-101***"
    userdata_interfaces:
    - name: "Ethernet2/0"
    - name: "Ethernet2/1"

    ############################################ Wap Interfaces ############################################
    wap_mgmt_pvid: "997"
    wap_vlan_range: "201,666,997"
    wap_int_desc: "***Meraki_WAP***"
    wap_interfaces:
    - name: "Ethernet2/2"
    - name: "Ethernet2/3"

    ############################################ Servers Interfaces ########################################

    server_interfaces:
    - name: "Ethernet1/2"
      description: "***Server***"
      vlan_range: "301"
      native_vid: "13"
    #- name: "Ethernet1/3"
    #  description: "***Server***"
    #  vlan_range: "301"
    #  native_vid: "13"


Asw02:
  hostname: 192.168.0.13
  groups:
    - cisco
    - s1
  data:
    site_code: s1
    device_role: access_switch      # Options:  "core_switch"  "access_switch" "wan_router"
    host_name: s1-asw02

    ############################################ VLANS ###################################################
    vlans:
      - name: Wired-Corp
        id: 101
      - name: Wireless-Corp
        id: 201
      - name: Servers
        id: 301
      - name: Wireless-Guest
        id: 666
      - name: Mgmt-Meraki-WAP
        id: 997
      - name: Mgmt-Cisco-SW
        id: 998
      - name: Trunk_Unused_Native_VLAN # Trunks only
        id: 13



    ############################################ SVI Interfaces ############################################
    svi_interfaces:
    - name: Vlan998
      description: "***ManagementPort-Vlan998***"
      ip: "10.1.253.5"
      sm: "255.255.255.0"

    ############################################ Static routes #############################################
    static_routes:
    - name: Default Route
      ip: "0.0.0.0"
      sm: "0.0.0.0"
      gw: "10.1.253.1"


    #uplink_interfaces:
    # name examples: Port-channel12 or GigabitEthernet2/0/11
    #- name: Port-channel1
    #  description: "***Uplink CSWxASW***"
    #  vlan_range: "101,201,301,666,997,998"
    #  native_vid: "13"


    port_channel_interfaces:
    - name: "Port-channel1"
      description: "***Uplink CSWxASW***"
      vlan_range: "101,201,301,666,997,998"
      #native_vid: "13"
      pono: "1"
      po_mode: "passive"
      po_int_members:
        - name: "Ethernet1/0"
          description: "***Uplink ASW01-e1/0 <--> CSW01-e1/0 - Po1***"
        - name: "Ethernet1/1"
          description: "***Uplink ASW01-e1/1 <--> CSW01-e1/1 - Po1***"

    ############################################ User Data Interfaces ########################################
    userdata_pvid: 101
    userdata_int_desc: "***UserDataVlan-101***"
    userdata_interfaces:
    - name: "Ethernet2/0"
    - name: "Ethernet2/1"

    ############################################ Wap Interfaces ############################################
    wap_mgmt_pvid: "997"
    wap_vlan_range: "201,666,997"
    wap_int_desc: "***Meraki_WAP***"
    wap_interfaces:
    - name: "Ethernet2/2"
    - name: "Ethernet2/3"

    ############################################ Servers Interfaces ########################################

    server_interfaces:
    - name: "Ethernet1/2"
      description: "***Server***"
      vlan_range: "301"
      native_vid: "13"
    #- name: "Ethernet1/3"
    #  description: "***Server***"
    #  vlan_range: "301"
    #  native_vid: "13"